- name: Create ZeroClaw directory
  ansible.builtin.file:
    path: /opt/services/zeroclaw
    state: directory
    mode: "0755"

- name: Create ZeroClaw data directory
  ansible.builtin.file:
    path: /opt/services/zeroclaw/data
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0750"

- name: Deploy ZeroClaw Compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/services/zeroclaw/compose.yml
    mode: "0644"

# Remember to add the folowing configs to make make it work with standalone image + host ui locally
# [runtime]
# kind = "docker"

# [gateway]
# host = "0.0.0.0"
# port = 42617
# allow_public_bind = true
# require_pairing = true

- name: Start ZeroClaw
  community.docker.docker_compose_v2:
    project_src: /opt/services/zeroclaw
    state: present