name: Run Ansible Playbook

on:
  push:
    branches: [main]

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.5.0
        with:
          submodules: recursive
        permissions:
          contents: read
      - name: Set up SSH known hosts and verify host key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.VPS_HOST_SSH_KEY }}" > ~/.ssh/tmp_key
          chmod 600 ~/.ssh/tmp_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          rm -f ~/.ssh/tmp_key
      - name: Run Ansible playbook
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ~/.ssh/tmp_key
          chmod 600 ~/.ssh/tmp_key
          ansible-playbook \
            --private-key="~/.ssh/tmp_key" \
            -i inventory/hosts.yml site.yml
          rm -f ~/.ssh/tmp_key
